[package]
edition = "2021"
name = "bollarddss"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bollard = "0.13.0"
futures = "0.3.24"
tokio = { version = "1.17.0", features = ["full"] }
