[package]
name = "bollarddss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bollard = "0.11.1"
futures = "0.1.31"
futures-util = "0.3.21"
tokio = { version = "1.17.0", features = ["full"] }
