[package]
name = "natural_cmp"
version = "0.1.0"
edition = "2021"
authors = ["Tejas Sanap<sanap.tejas@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
