[package]
name = "make_my_tar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-tar = "0.3.0"
tokio = { version = "1.15.0", features = ["full"] }
futures = "0.3.19"
