[package]
name = "squeeze-my-cpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "1.0.4"
rayon = "1.7.0"
tokio = { version = "1.27.0", features = ["full"] }
futures = "0.3.28"
